version: '3'
services:
  sample-prod:
    container_name: thumb-react-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}