version: '3'
services:
  cboe-react:
    container_name: cboe-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}