version: "3"
services:
  website:
    build: .
    working_dir: /usr/share/nginx/html/
    environment:
    - NODE_ENV=${NODE_ENV}
    - VUE_APP_REGION=${VUE_APP_REGION}
    - VUE_APP_AWS_ACCESS_KEY_ID=${VUE_APP_AWS_ACCESS_KEY_ID}
    - VUE_APP_AWS_SECRET_ACCESS_KEY=${VUE_APP_AWS_SECRET_ACCESS_KEY}
    - VUE_APP_BUCKET_FULL=${VUE_APP_BUCKET_FULL}
    - VUE_APP_BUCKET_THUMB=${VUE_APP_BUCKET_THUMB}
    - VUE_APP_CEPH_ENDPOINT=${VUE_APP_CEPH_ENDPOINT}
    volumes:
    - .:/app
    networks:
    - internal
    - proxy
    labels:
    - "traefik.port=80"
    - "traefik.backend=website"
    - "traefik.frontend.rule=Host:thumbviewer.local;Path:/images, images/{id:[0-9]+}, images/{id:[0-9]+}/{id:[0-9]+}, /sql,/history, /info"
    - traefik.docker.network=proxy
  reverse-proxy:
    container_name: traefik
    image: traefik:1.7.6-alpine  # The official Traefik docker image
    command: --api --docker --logLevel=INFO # Enables the web UI and tells Traefik to listen to docker
    networks:
    - proxy
    labels:
    - "traefik.port=80"
    - "traefik.backend=traefik-dashboard"
    - "traefik.frontend.rule=Host:traefik-dashboard.dev"
    - traefik.docker.network=proxy
    ports:
    - "80:80"      # The HTTP port
    - "443:443"    # The HTTPS port
    - "8081:8080"  # The Web UI (enabled by --api)
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
    - $PWD/traefik.toml:/traefik.toml
    - $PWD/acme.json:/acme.json

networks:
  proxy:
    external: true
  internal:
    external: false